version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.frank
    user: "root"
    ports:
      - "8080:80"
      - "443:443"
      - "443:443/udp" # Required for HTTP/3 speeds
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    environment:
      - SERVER_NAME=localhost
      - MAX_REQUESTS=2000
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G


networks:
  app-network:
    driver: bridge
